### ISSUE TITLE
Syntax error in meta/main.yml dependencies

### ISSUE THREAD

**Issue by chuck-confluent** [andrewrothstein/ansible-kubernetes-helm#11]
Ansible is complaining about a syntax error here: https://github.com/andrewrothstein/ansible-kubernetes-helm/blob/master/meta/main.yml#L2 . I think some indentation is off

**Comment by andrewrothstein** [comment]
I yamllinted/degreased it. Try v2.0.2 and lmk if it's still unhappy. Ansible is pretty generous about the ugliness of the YaML.

**Comment by chuck-confluent** [comment]
Sorry, it turned out to be some strange ansible version conflicts on my end. I purged all ansible from my system, re-installed, and have now successfully been able to install your helm role recursively.

Thanks so much for putting these roles together (this one and the k3d one)! They made it super simple for me to throw together a nice local kubernetes environment. Cheers!
