### ISSUE TITLE
Update default Helm version to 2.12.2

### ISSUE THREAD

**Issue by rdonkin** [andrewrothstein/ansible-kubernetes-helm#4]
Since 2.12.2 fixes a significant security issue, I think this should be the default version in `defaults/main.yml`, not 2.12.0.

**Comment by andrewrothstein** [comment]
I agree. This was an oversight on my last commit

**Comment by andrewrothstein** [comment]
published v1.2.11 to the galaxy with helm v2.12.2 as the default
